variable vpc_id {}
variable subnet_id {}
variable my_ip {}
variable env_prefix {}
variable public_key_path {}
variable instance_type {}
variable av_zone {}
variable ssh_user {}
variable private_key_path {}
